import "~/styles/globals.css";
import { type Metadata } from "next";
import { Libre_Baskerville } from "next/font/google";

const baskervville = Libre_Baskerville({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-libre-baskerville",
});

export const metadata: Metadata = {
  title: "Kapil Jewels",
  description: "Generated by create-t3-app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${baskervville.variable}`}>
      <body>{children}</body>
    </html>
  );
}
