import "~/styles/globals.css";
import { DesktopNav, MobileNav } from "~/app/_components/navigation";
import { paymentIcons } from "~/app/_components/payment-icons";
import Search from "~/app/_components/search";
import { ShoppingBag } from "~/app/_components/shoping-bag";
import { TRPCReactProvider } from "~/trpc/react";
import { Copyright, Facebook, Instagram, UserCircle2 } from "lucide-react";
import { type Metadata } from "next";
import { Link, ViewTransitions } from "next-view-transitions";
import { Libre_Baskerville } from "next/font/google";

const baskervville = Libre_Baskerville({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-libre-baskerville",
});

export const metadata: Metadata = {
  title: "Kapil Jewels",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function LocaleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" className={`${baskervville.variable}`}>
        <body>
          <div className="flex flex-col items-center bg-orange-200 p-2 text-lg">
            <p>FAMILY OWNED AND OPERATED</p>
            <Link
              href="/about"
              className="relative outline-hidden after:absolute after:inset-x-0 after:bottom-0 after:h-[2px] after:bg-black after:transition-transform after:duration-300 hover:after:scale-x-[.85] focus-visible:after:scale-x-[.85]"
            >
              More about us
            </Link>
          </div>
          <div className="flex items-center justify-between border-b-[1px] px-8 py-2">
            <MobileNav />
            <Link
              href="/"
              className="font-libre-baskerville flex flex-col items-center font-medium select-none"
            >
              <span className="text-4xl">KAPIL</span>
              <span className="text-xl">JEWELS</span>
            </Link>
            <div className="flex gap-4">
              <Link href="/account">
                <UserCircle2 aria-hidden={true} strokeWidth={1} />
                <span className="sr-only">account</span>
              </Link>
              <Search />
              <Link href="/card">
                <ShoppingBag aria-hidden={true} />
                <span className="sr-only">cart</span>
              </Link>
            </div>
          </div>
          <DesktopNav />
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <footer className="bg-muted p-6 sm:p-12">
            <div className="flex justify-between max-sm:flex-col">
              <div>
                <p className="font-libre-baskerville text-2xl">Contacts</p>
                <div className="my-6 flex flex-col gap-2 text-sm">
                  <Link
                    href="mailto:info@kapiljewels.com"
                    className="underline underline-offset-2"
                  >
                    info@kapiljewels.com
                  </Link>
                  <p>Jaipur</p>
                  <Link href="tel:+91-9876543210">+91-9876543210</Link>
                  <div className="flex gap-2">
                    <Link href="#">
                      <Facebook
                        className="size-5"
                        strokeWidth={1}
                        aria-hidden={true}
                      />
                      <span className="sr-only">facebook</span>
                    </Link>
                    <Link href="#">
                      <Instagram
                        className="size-5"
                        strokeWidth={1}
                        aria-hidden={true}
                      />
                      <span className="sr-only">instagram</span>
                    </Link>
                  </div>
                </div>
              </div>
              <div>
                <p className="font-libre-baskerville text-2xl">Get inspired</p>
                <div className="my-6 text-sm">
                  <span>#kapiljewels</span>
                  <p className="mt-2">@kapil.jewels</p>
                </div>
              </div>
            </div>
            <div className="flex justify-between max-xl:flex-col max-xl:gap-2">
              <div className="flex flex-wrap gap-4 text-sm">
                <Link href="/" className="flex items-center gap-1">
                  <Copyright className="size-3.5" strokeWidth={1.5} />
                  Kapil Jewels {new Date().getFullYear()}
                </Link>
                <Link href="/shipping-policy">Shipping</Link>
                <Link href="/about">About</Link>
                <Link href="/refund-policy">Customer Service</Link>
                <Link href="/terms-of-service">Terms & Conditions</Link>
                <Link href="/contact">Contact</Link>
              </div>
              <div className="flex flex-wrap gap-2">
                {paymentIcons.map(({ PaymentIcon, name }) => (
                  <PaymentIcon key={name} aria-label={name} />
                ))}
              </div>
            </div>
          </footer>
        </body>
      </html>
    </ViewTransitions>
  );
}
